FROM apache/airflow:2.10.3-python3.11

USER root
# Spark needs a JVM
RUN apt-get update && apt-get install -y --no-install-recommends openjdk-17-jre-headless \
    && apt-get clean && rm -rf /var/lib/apt/lists/* \
    && ln -s "$(dirname "$(dirname "$(readlink -f "$(which java)")")")" /usr/lib/jvm/default-java
# works on both Apple Silicon (arm64) and Intel (amd64) images
ENV JAVA_HOME=/usr/lib/jvm/default-java
USER airflow

COPY pyproject.toml /opt/airflow/project/pyproject.toml
COPY src /opt/airflow/project/src
RUN pip install --no-cache-dir -e /opt/airflow/project "apache-airflow-providers-amazon"
